TERMO DE COMPROMISSO
AUNIÃOBRASILEIRADEEDUCAÇÃOEASSISTÊNCIA,mantenedoradaPontifíciaUniversidadeCatólicadoRioGrandedoSul,inscritanosobCNPJnº88.630.413/0002-81,comsedenaAvenidaIpiranga,nº6681,BairroPartenon,PortoAlegre/RS,doravantedenominadasimplesmenteUBEA/PUCRS,nesteatorepresentadaporseuprocuradoraofinalassinado;eoacadêmicoArthurSchosslerDutradocursodeGraduaçãoemEngenhariadeSoftware,devidamentematriculadoemcursooferecidopelaIESUBEA/PUCRSsobonº19103433-9,inscritosobCPFnº041.653.110-57,portadordoRG nº4101256818,residenteedomiciliadonologradouroRuaIntendenteAlfredoAzevedonº399,complementoCasa28,bairroGlória,cidadePortoAlegre/RS,doravantedenominado simplesmente BOLSISTA;
Resolvem firmar o presente Termo de Compromisso de acordo com as seguintes cláusulas:
CLÁUSULA PRIMEIRA – DO CONCEITO E DOS OBJETIVOS
1.1EsteinstrumentotemporobjetoestabeleceroconceitoeascondiçõesdeparticipaçãodoBOLSISTAnasatividadesdeestudo,pesquisaedesenvolvimento,previstasnoprojetointitulado“ITAcademy2020:CapacitaçãoemTecnologiadaInformação”,realizadoemparceriacomaempresa/instituiçãoDELL,conformeencontra-seprevistonoConvênio/TermoAditivoTA12/2020-ITAcademy 2020, adiante denominado simplesmente PROJETO.
1.2Abolsaéumapoiofinanceiroconcedidopelaempresa/instituiçãocomoauxílioaumestudanteregularmentematriculadoemumprogramadepós-graduaçãodaUBEA/PUCRSparasuaparticipaçãoematividadedepesquisaemprojetosemparceriaentreaempresa/instituiçãoeaUBEA/PUCRS,possibilitando-lhevivênciapráticanaáreadepesquisa,visandoaprimoramentoequalidadeda formação acadêmica proporcionada pela Universidade.
1.3 Mediante a assinatura do presente instrumento a UBEA/PUCRS autoriza o BOLSISTA a atuar no PROJETO.
1.4 MedianteaassinaturadopresenteinstrumentooBOLSISTAdeclaraqueonúmerodehorasquesededicaráaoPROJETO,écompatívelcomasuacargahoráriacomoalunonaUBEA/PUCRSequenãoreceberáqualquertipodebolsaouremuneração,alémda prevista aqui, salvo autorização formal da UBEA/PUCRS, conforme previsto no item 3.6.1. abaixo.
CLÁUSULA SEGUNDA – DAS OBRIGAÇÕES DA UBEA/PUCRS
Compete à UBEA/PUCRS:
2.1.RealizarorepassedosrecursosprevistosnoprojetoaoBOLSISTA,conformeestabelecidonesteinstrumentoenoConvênio/Termo Aditivo TA 12/2020 - IT Academy 2020
2.2.Receber,orientar,supervisionarecontrolarasatividadesdoBOLSISTAdando-lhecondiçõesparaquerealizeassuasatividades de acordo com os objetivos do PROJETO.
CLÁUSULA TERCEIRA – DAS OBRIGAÇÕES DO BOLSISTA
Compete ao BOLSISTA:
3.1. Assumir o compromisso de atuar como BOLSISTA sem prejuízo de seus estudos junto à UBEA/PUCRS;
3.2.Portar-seconformeamelhoréticaestudantileprofissionalnolocaldeexecuçãodesuastarefascomoBOLSISTAfrenteaoPROJETO;
3.3.ObservarohoráriodefinidopelaUBEA/PUCRSparadesenvolverassuasatividadesemconformidadecomacargahoráriadefinida na cláusula sétima;
3.4.Elaborartrimestralmenteumrelatóriodesuasatividades,nacondiçãodeBOLSISTAdoPROJETO,quedeveráserentregueaoCoordenador do PROJETO indicado pela UBEA/PUCRS.
3.5. Manter desempenho acadêmico satisfatório durante o período em que atuar como BOLSISTA do PROJETO.
3.6.InformaraUBEA/PUCRScasovenhaadesenvolverduranteavigênciadesteTermodeCompromissoqualqueratividaderemunerada.
3.6.1.OBOLSISTApoderárecebercomplementaçãofinanceira,provenientedeoutrasfontes,desdequesedediqueaatividadesrelacionadasàsuaáreadeatuaçãoedeinteresseparasuaformaçãoacadêmica,científicaetecnológica,especialmentequandosetratar de docência como professora nos ensinos de qualquer grau.
3.6.1.1.Pararecebercomplementaçãofinanceiraouatuarcomodocente,oBOLSISTAdeveobterautorização,concedidaporseuorientador, sendo devidamente informado a GESTÃO DE PROJETOS da PUCRS, Unidade Universitária da UBEA/PUCRS.
3.6.1.2.Nocasodecomprovadodesrespeitoàscondiçõesestabelecidasnesteitem3.6.oBOLSISTAseráobrigadoadevolveraUBEA/PUCRS os valores recebidos a título de bolsa.
3.7. Respeitar e submeter-se:
3.7.1. Às orientações técnicas e administrativas do coordenador do PROJETO;
3.7.2. Ao acompanhamento e avaliação de seu desempenho durante o período de vigência deste Termo;
3.8.Manterabsolutosigiloeconfidencialidadesobretodasasinformaçõesrecebidaseaquetiveracessoemdecorrênciadasuaparticipação no PROJETO.